### ISSUE TITLE
Salvar dados crawleados em um banco de dados

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/maria-quiteria#22]
Salvar dados dos atuais spiders:

- [x] Agenda da Câmara Municipal.
- [ ] Contratos da Prefeitura (#63)
- [x] Diário Oficial (incluindo o legado) da Prefeitura/Câmara de Vereadores
- [ ] Licitações da Prefeitura (#69)
- [ ] Pagamentos da Prefeitura (#70)

**Comment by anapaulagomes** [comment]
Fechando essa issue já que existem issues específicas para cada base de dados.
